routes/admin.php
<?php

Route::group(['prefix' => 'inside', 'as' => 'admin.'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::post('upload-image', 'CkeditorController@upload')->name('ckeditor.upload');

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::resource('office', 'OfficeController')->except(['show']);
        Route::resource('banner', 'BannerController')->except(['show']);
        Route::post('banner/reorder', 'BannerController@reorder')->name('banner.reorder');

        Route::resource('partner', 'PartnerController')->except(['show']);
        Route::post('partner/reorder', 'PartnerController@reorder')->name('partner.reorder');

        Route::resource('feedback', 'FeedbackController')->except(['show', 'create', 'store']);

        Route::resource('vacancy', 'VacancyController')->except(['show']);
        Route::post('vacancy/reorder', 'VacancyController@reorder')->name('vacancy.reorder');
        Route::get('vacancy/{vacancy}/responses', 'VacancyController@responses')->name('vacancy.responses');
        Route::get('vacancy/{vacancy}/response/{response}', 'VacancyController@response')->name('vacancy.response.show');

        Route::group(['prefix' => 'article', 'as' => 'article.'], function () {
            Route::resource('category', 'Article\ArticleCategoryController')->except(['show']);
            Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
                Route::resource('{category}/translation', 'Article\ArticleCategoryTranslationController')->except(['index', 'show']);
            });
            Route::resource('article', 'Article\ArticleController')->except(['show']);
            Route::group(['prefix' => 'article/{article}', 'as' => 'article.'], function () {
                Route::resource('translation', 'Article\ArticleTranslationController')->except(['index', 'show']);
            });
        });

        Route::group(['prefix' => 'catalog', 'as' => 'catalog.'], function () {
            Route::resource('producer', 'Catalog\CatalogProducerController')->except(['show']);
            Route::post('producer/reorder', 'Catalog\CatalogProducerController@reorder')->name('producer.reorder');

            Route::resource('category', 'Catalog\CatalogCategoryController')->except(['show']);
            Route::post('category/reorder', 'Catalog\CatalogCategoryController@reorder')->name('category.reorder');
            Route::post('attribute/reorder', 'Catalog\CatalogAttributeController@reorder')->name('attribute.reorder');
            Route::group(['prefix' => 'category/{category}', 'as' => 'category.'], function () {
                Route::resource('attribute', 'Catalog\CatalogAttributeController')->except(['index', 'show']);
                Route::resource('translation', 'Catalog\CatalogCategoryTranslationController')->except(['index', 'show']);
            });

            Route::resource('culture', 'Catalog\CatalogCultureController')->except(['show']);
            Route::post('culture/reorder', 'Catalog\CatalogCultureController@reorder')->name('culture.reorder');
            Route::group(['prefix' => 'culture/{culture}', 'as' => 'culture.'], function () {
                Route::resource('translation', 'Catalog\CatalogCultureTranslationController')->except(['index', 'show']);
            });

            Route::resource('section', 'Catalog\CatalogSectionController')->except(['show']);
            Route::post('section/reorder', 'Catalog\CatalogSectionController@reorder')->name('section.reorder');
            Route::group(['prefix' => 'section/{section}', 'as' => 'section.'], function () {
                Route::resource('translation', 'Catalog\CatalogSectionTranslationController')->except(['index', 'show']);
            });

            Route::resource('protection', 'Catalog\CatalogProtectionController')->except(['show']);
            Route::group(['prefix' => 'protection/{protection}', 'as' => 'protection.'], function () {
                Route::resource('translation', 'Catalog\CatalogProtectionTranslationController')->except(['index', 'show']);
            });

            Route::resource('disease', 'Catalog\CatalogDiseaseController')->except(['show']);
            Route::group(['prefix' => 'disease/{disease}', 'as' => 'disease.'], function () {
                Route::resource('translation', 'Catalog\CatalogDiseaseTranslationController')->except(['index', 'show']);
            });

            Route::resource('substance', 'Catalog\CatalogSubstanceController')->except(['show']);
            Route::group(['prefix' => 'substance/{substance}', 'as' => 'substance.'], function () {
                Route::resource('translation', 'Catalog\CatalogSubstanceTranslationController')->except(['index', 'show']);
            });

            Route::group(['prefix' => 'product'], function () {
                Route::get('/', 'Catalog\CatalogProductController@index')->name('product.index');
                Route::get('create/{category}', 'Catalog\CatalogProductController@create')->name('product.create');
                Route::post('store/{category}', 'Catalog\CatalogProductController@store')->name('product.store');
                Route::get('{product}/edit', 'Catalog\CatalogProductController@edit')->name('product.edit');
                Route::put('{product}/update/{category}', 'Catalog\CatalogProductController@update')->name('product.update');
                Route::delete('{product}/destroy', 'Catalog\CatalogProductController@destroy')->name('product.destroy');
                Route::group(['prefix' => '{product}', 'as' => 'product.'], function () {
                    Route::resource('translation', 'Catalog\CatalogProductTranslationController')->except(['index', 'show']);
                });
            });

            Route::get('import', 'Catalog\CatalogImportController@form')->name('import.form');
            Route::post('import', 'Catalog\CatalogImportController@store')->name('import.store');
        });
    });
});

routes/web.php
<?php

Route::get('/', 'MainController@index')->name('home');
Route::get('about', 'PageController@about')->name('about');
Route::get('contact', 'PageController@contact')->name('contact');
Route::get('consult', 'PageController@consult')->name('consult');
Route::get('career', 'PageController@career')->name('career');
Route::get('internship', 'PageController@internship')->name('internship');

Route::post('feedback/main', 'FeedbackController@main')->name('feedback.main');
Route::post('feedback/internship', 'FeedbackController@internship')->name('feedback.internship');
Route::post('feedback/vacancy', 'FeedbackController@vacancy')->name('feedback.vacancy');
Route::post('feedback/product', 'FeedbackController@product')->name('feedback.product');

Route::get('search', 'SearchController@search')->name('search');

Route::group(['prefix' => 'article'], function () {
    Route::get('/', 'ArticleController@index')->name('article.index');
    Route::get('{article_category}', 'ArticleController@category')->name('article.category');
    Route::get('{article_category}/{article_slug}', 'ArticleController@article')->name('article.article');
});

Route::group(['prefix' => 'catalog'], function () {
    Route::get('/', 'CatalogController@index')->name('catalog.index');

    Route::group(['prefix' => '{country_code}'], function () {
        Route::get('/', 'CatalogController@main')->name('catalog.main');
        Route::get('/{catalog_category}', 'CatalogController@category')->name('catalog.category');
        Route::get('/{section_path}', 'CatalogController@section')->where('section_path', '^(?:(?!\/product).)+')->name('catalog.section');
        Route::get('/{product_path}', 'CatalogController@product')->where('product_path', '.+')->name('catalog.product');
    });
});

Route::group(['prefix' => 'culture'], function () {
    Route::get('/', 'CultureController@index')->name('culture.index');
    Route::get('/{catalog_category}', 'CultureController@category')->name('culture.category');
    Route::get('/{catalog_category}/{culture_path}', 'CultureController@culture')
        ->where('culture_path', '.+')
        ->name('culture.culture');
});

Route::group(['prefix' => 'protection'], function () {
    Route::get('/', 'ProtectionController@index')->name('protection.index');
});

Route::get('sitemap.xml', 'SitemapController@sitemap');

resources/views/admin/catalog/culture/translation/_form.blade.php
<div class="card">
    <div class="card-header">
        <div class="card-header__actions">
            <a href="{{ route('admin.catalog.culture.edit', $culture) }}" class="btn btn-secondary">
                <i class="fa fa-arrow-left"></i>
                <span class="hidden-xs hidden-sm">Вернуться</span>
            </a>
            @if (isset($cultureTranslation) && isset($mode) && $mode === 'edit')
                <button class="btn btn-danger"
                        title="Удалить"
                        data-action="destroy"
                        data-href="{{ route('admin.catalog.culture.translation.destroy', [$culture, $cultureTranslation]) }}">
                    <i class="fa fa-trash"></i>
                    <span>Удалить перевод</span>
                </button>
            @endif
            <button type="submit" class="btn-success btn"><i class="fa fa-save"></i> <span>Сохранить</span></button>
        </div>
    </div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">Ошибка валидации</div>
        @endif
        <div class="form-group {{ $errors->has('locale') ? 'is-invalid' : '' }}">
            <label class="col-form-label">Язык</label>
            <select name="locale" class="form-control select2">
                @foreach ($locales as $langCode => $locale)
                    <option value="{{ $langCode }}"
                        {{ (isset($cultureTranslation) && $cultureTranslation->locale == $langCode) || old('locale') == $langCode ? 'selected' : '' }}>
                        {{ $locale['title'] }}
                    </option>
                @endforeach
            </select>
            {!! $errors->first('locale','<span class="invalid-feedback">:message</span>') !!}
        </div>
        <div class="form-group {{ $errors->has('title') ? 'is-invalid' : '' }}">
            <label class="col-form-label">Заголовок</label>
            <input name="title" type="text" class="form-control" value="{{ isset($cultureTranslation) ? $cultureTranslation->title : old('title') }}">
            {!! $errors->first('title','<span class="invalid-feedback">:message</span>') !!}
        </div>
        <div class="form-group {{ $errors->has('slug') ? 'is-invalid' : '' }}">
            <label class="col-form-label">Slug (алиас в URL)</label>
            <input name="slug" type="text" class="form-control" value="{{ isset($cultureTranslation) ? $cultureTranslation->slug : old('slug') }}">
            {!! $errors->first('slug','<span class="invalid-feedback">:message</span>') !!}
        </div>
        <div class="form-group {{ $errors->has('description') ? 'is-invalid' : '' }}">
            <label class="col-form-label">Описание</label>
            <textarea name="description" class="form-control" rows="3">{{ isset($cultureTranslation) ? $cultureTranslation->description : old('description') }}</textarea>
            {!! $errors->first('description','<span class="invalid-feedback">:message</span>') !!}
        </div>
        @include('admin.partial.seo_fields', ['seoData' => isset($seoData) ? $seoData : null])
    </div>
</div>

resources/views/admin/catalog/culture/translation/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="page-title-area">
        <h4 class="page-title">Каталог - Культуры</h4>
        <ul class="breadcrumbs">
            <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
            <li><a href="{{ route('admin.catalog.culture.index') }}">Каталог - Все культуры</a></li>
            <li><a href="{{ route('admin.catalog.culture.edit', $culture) }}">{{ $culture->title }}</a></li>
            <li><span>Создать перевод</span></li>
        </ul>
    </div>
    <div class="main-content-inner">
        <form action="{{ route('admin.catalog.culture.translation.store', $culture) }}" enctype="multipart/form-data" method="POST">
            {{ csrf_field() }}
            @include('admin.catalog.culture.translation._form', ['mode' => 'create'])
        </form>
    </div>
@endsection

resources/views/admin/catalog/culture/translation/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="page-title-area">
        <h4 class="page-title">Каталог - Культуры</h4>
        <ul class="breadcrumbs">
            <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
            <li><a href="{{ route('admin.catalog.culture.index') }}">Каталог - Все культуры</a></li>
            <li><a href="{{ route('admin.catalog.culture.edit', $culture) }}">{{ $culture->title }}</a></li>
            <li><span>Перевод</span></li>
        </ul>
    </div>
    <div class="main-content-inner">
        <form action="{{ route('admin.catalog.culture.translation.update', [$culture, $cultureTranslation]) }}" enctype="multipart/form-data" method="POST">
            {{ csrf_field() }}
            @method('PUT')
            @include('admin.catalog.culture.translation._form', ['mode' => 'edit'])
        </form>
    </div>
@endsection