routes/admin.php
<?php

Route::group(['prefix' => 'inside', 'as' => 'admin.'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::post('upload-image', 'CkeditorController@upload')->name('ckeditor.upload');

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::resource('office', 'OfficeController')->except(['show']);
        Route::resource('banner', 'BannerController')->except(['show']);
        Route::post('banner/reorder', 'BannerController@reorder')->name('banner.reorder');

        Route::resource('partner', 'PartnerController')->except(['show']);
        Route::post('partner/reorder', 'PartnerController@reorder')->name('partner.reorder');

        Route::resource('feedback', 'FeedbackController')->except(['show', 'create', 'store']);

        Route::resource('vacancy', 'VacancyController')->except(['show']);
        Route::post('vacancy/reorder', 'VacancyController@reorder')->name('vacancy.reorder');
        Route::get('vacancy/{vacancy}/responses', 'VacancyController@responses')->name('vacancy.responses');
        Route::get('vacancy/{vacancy}/response/{response}', 'VacancyController@response')->name('vacancy.response.show');

        Route::group(['prefix' => 'article', 'as' => 'article.'], function () {
            Route::resource('category', 'Article\ArticleCategoryController')->except(['show']);
            Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
                Route::resource('{category}/translation', 'Article\ArticleCategoryTranslationController')->except(['index', 'show']);
            });
            Route::resource('article', 'Article\ArticleController')->except(['show']);
            Route::group(['prefix' => 'article/{article}', 'as' => 'article.'], function () {
                Route::resource('translation', 'Article\ArticleTranslationController')->except(['index', 'show']);
            });
        });

        Route::group(['prefix' => 'catalog', 'as' => 'catalog.'], function () {
            Route::resource('producer', 'Catalog\CatalogProducerController')->except(['show']);
            Route::post('producer/reorder', 'Catalog\CatalogProducerController@reorder')->name('producer.reorder');

            Route::resource('category', 'Catalog\CatalogCategoryController')->except(['show']);
            Route::post('category/reorder', 'Catalog\CatalogCategoryController@reorder')->name('category.reorder');
            Route::post('attribute/reorder', 'Catalog\CatalogAttributeController@reorder')->name('attribute.reorder');
            Route::group(['prefix' => 'category/{category}', 'as' => 'category.'], function () {
                Route::resource('attribute', 'Catalog\CatalogAttributeController')->except(['index', 'show']);
                Route::resource('translation', 'Catalog\CatalogCategoryTranslationController')->except(['index', 'show']);
            });

            Route::resource('culture', 'Catalog\CatalogCultureController')->except(['show']);
            Route::post('culture/reorder', 'Catalog\CatalogCultureController@reorder')->name('culture.reorder');
            Route::group(['prefix' => 'culture/{culture}', 'as' => 'culture.'], function () {
                Route::resource('translation', 'Catalog\CatalogCultureTranslationController')->except(['index', 'show']);
            });

            Route::resource('section', 'Catalog\CatalogSectionController')->except(['show']);
            Route::post('section/reorder', 'Catalog\CatalogSectionController@reorder')->name('section.reorder');
            Route::group(['prefix' => 'section/{section}', 'as' => 'section.'], function () {
                Route::resource('translation', 'Catalog\CatalogSectionTranslationController')->except(['index', 'show']);
            });

            Route::resource('protection', 'Catalog\CatalogProtectionController')->except(['show']);
            Route::group(['prefix' => 'protection/{protection}', 'as' => 'protection.'], function () {
                Route::resource('translation', 'Catalog\CatalogProtectionTranslationController')->except(['index', 'show']);
            });

            Route::resource('disease', 'Catalog\CatalogDiseaseController')->except(['show']);
            Route::group(['prefix' => 'disease/{disease}', 'as' => 'disease.'], function () {
                Route::resource('translation', 'Catalog\CatalogDiseaseTranslationController')->except(['index', 'show']);
            });

            Route::resource('substance', 'Catalog\CatalogSubstanceController')->except(['show']);
            Route::group(['prefix' => 'substance/{substance}', 'as' => 'substance.'], function () {
                Route::resource('translation', 'Catalog\CatalogSubstanceTranslationController')->except(['index', 'show']);
            });

            Route::group(['prefix' => 'product'], function () {
                Route::get('/', 'Catalog\CatalogProductController@index')->name('product.index');
                Route::get('create/{category}', 'Catalog\CatalogProductController@create')->name('product.create');
                Route::post('store/{category}', 'Catalog\CatalogProductController@store')->name('product.store');
                Route::get('{product}/edit', 'Catalog\CatalogProductController@edit')->name('product.edit');
                Route::put('{product}/update/{category}', 'Catalog\CatalogProductController@update')->name('product.update');
                Route::delete('{product}/destroy', 'Catalog\CatalogProductController@destroy')->name('product.destroy');
                Route::group(['prefix' => '{product}', 'as' => 'product.'], function () {
                    Route::resource('translation', 'Catalog\CatalogProductTranslationController')->except(['index', 'show']);
                });
            });

            Route::get('import', 'Catalog\CatalogImportController@form')->name('import.form');
            Route::post('import', 'Catalog\CatalogImportController@store')->name('import.store');
        });
    });
});

routes/web.php
<?php

Route::get('/', 'MainController@index')->name('home');
Route::get('about', 'PageController@about')->name('about');
Route::get('contact', 'PageController@contact')->name('contact');
Route::get('consult', 'PageController@consult')->name('consult');
Route::get('career', 'PageController@career')->name('career');
Route::get('internship', 'PageController@internship')->name('internship');

Route::post('feedback/main', 'FeedbackController@main')->name('feedback.main');
Route::post('feedback/internship', 'FeedbackController@internship')->name('feedback.internship');
Route::post('feedback/vacancy', 'FeedbackController@vacancy')->name('feedback.vacancy');
Route::post('feedback/product', 'FeedbackController@product')->name('feedback.product');

Route::get('search', 'SearchController@search')->name('search');

Route::group(['prefix' => 'article'], function () {
    Route::get('/', 'ArticleController@index')->name('article.index');
    Route::get('{article_category}', 'ArticleController@category')->name('article.category');
    Route::get('{article_category}/{article_slug}', 'ArticleController@article')->name('article.article');
});

Route::group(['prefix' => 'catalog'], function () {
    Route::get('/', 'CatalogController@index')->name('catalog.index');

    Route::group(['prefix' => '{country_code}'], function () {
        Route::get('/', 'CatalogController@main')->name('catalog.main');
        Route::get('/{catalog_category}', 'CatalogController@category')->name('catalog.category');
        Route::get('/{section_path}', 'CatalogController@section')->where('section_path', '^(?:(?!\/product).)+')->name('catalog.section');
        Route::get('/{product_path}', 'CatalogController@product')->where('product_path', '.+')->name('catalog.product');
    });
});

Route::group(['prefix' => 'culture'], function () {
    Route::get('/', 'CultureController@index')->name('culture.index');
    Route::get('/{catalog_category}', 'CultureController@category')->name('culture.category');
    Route::get('/{catalog_category}/{culture_path}', 'CultureController@culture')
        ->where('culture_path', '.+')
        ->name('culture.culture');
});

Route::group(['prefix' => 'protection'], function () {
    Route::get('/', 'ProtectionController@index')->name('protection.index');
});

Route::get('sitemap.xml', 'SitemapController@sitemap');

app/Models/Catalog/CatalogAttribute.php
<?php

namespace App\Models\Catalog;

use Illuminate\Database\Eloquent\Model;

class CatalogAttribute extends Model
{
    protected $table = 'catalog_attributes';
    public $timestamps = false;
    protected $fillable = ['name', 'locale', 'type', 'required', 'default', 'options', 'sort', 'is_filtered'];
    protected $casts = [
        'options' => 'array',
    ];

    const TYPE_STRING = 'string';
    const TYPE_INTEGER = 'integer';
    const TYPE_FLOAT = 'float';

    public static function listTypes(): array
    {
        return [
            self::TYPE_STRING => 'Строка',
            self::TYPE_INTEGER => 'Число',
            self::TYPE_FLOAT => 'Число с плавающей точкой',
        ];
    }

    public function isString(): bool
    {
        return $this->type === self::TYPE_STRING;
    }

    public function isInteger(): bool
    {
        return $this->type === self::TYPE_INTEGER;
    }

    public function isFloat(): bool
    {
        return $this->type === self::TYPE_FLOAT;
    }

    public function isNumber(): bool
    {
        return $this->isInteger() || $this->isFloat();
    }

    public function isSelect(): bool
    {
        return !is_null($this->options) && count($this->options) > 0;
    }
}

app/Models/Catalog/CatalogCategory.php
<?php

namespace App\Models\Catalog;

use App\Models\MainModel;
use App\Models\SeoManager;
use App\Traits\Seoable;
use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Builder;

class CatalogCategory extends MainModel
{
    use Translatable, Seoable;

    protected $guarded = ['id'];

    public $translationModel = CatalogCategoryTranslation::class;
    public $translationForeignKey = 'category_id';
    public $translatedAttributes = [
        'title', 'slug', 'description', 'status'
    ];

    const CATEGORY_SEMENA_ID = 1;
    const CATEGORY_FERTILIZER_ID = 2;
    const CATEGORY_PROTECTION_ID = 3;

    public function attributes()
    {
        return $this->hasMany(CatalogAttribute::class, 'category_id', 'id')->orderBy('sort');
    }

    public function diseases()
    {
        return $this->hasMany(CatalogDisease::class, 'category_id');
    }

    public function substances()
    {
        return $this->hasMany(CatalogSubstance::class, 'category_id');
    }

    public function sections()
    {
        return $this->hasMany(CatalogSection::class, 'category_id')->orderBy('position')->orderBy('created_at');
    }

    public function seo()
    {
        return $this->morphMany(SeoManager::class, 'seoable');
    }

    public function isSemena()
    {
        return $this->id == self::CATEGORY_SEMENA_ID;
    }

    public function isFertilizer()
    {
        return $this->id == self::CATEGORY_FERTILIZER_ID;
    }

    public function isProtection()
    {
        return $this->id == self::CATEGORY_PROTECTION_ID;
    }

    public function scopePublished(Builder $query)
    {
        return $query->where('status', self::STATUS_PUBLISHED);
    }

    public function scopeActiveTranslation(Builder $query, $locale = null)
    {
        $currentLocale = !is_null($locale) ? $locale : app()->getLocale();

        return $query->where(function($query) use ($currentLocale) {
            $query->orWhereHas('translations', function($query) use ($currentLocale) {
                $query->where('locale', $currentLocale);
                $query->where('status', self::STATUS_PUBLISHED);
                $query->select('status', 'locale', 'slug', 'category_id');
            })->orWhere(function($query) use ($currentLocale) {
                $query->orWhere('locale', $currentLocale);
                $query->where('status', self::STATUS_PUBLISHED);
            });
        });
    }

    public function resolveSlugBinding($value)
    {
        $value = trim($value, '/');

        return self::where(function ($query) use ($value) {
                $query->orWhereHas('translations', function($query) use ($value) {
                    $query->where('locale', app()->getLocale());
                    $query->where('slug', $value);
                    $query->where('status', self::STATUS_PUBLISHED);
                })->orWhere(function($query) use ($value) {
                    $query->orWhere('locale', app()->getLocale());
                    $query->where('slug', $value);
                    $query->where('status', self::STATUS_PUBLISHED);
                });
            })
            ->with('translations')
            ->firstOrFail();
    }
}

app/Models/Catalog/CatalogCategoryTranslation.php
<?php

namespace App\Models\Catalog;

use App\Models\MainModel;

class CatalogCategoryTranslation extends MainModel
{
    protected $guarded = ['id'];
}

app/Models/Catalog/CatalogCulture.php
<?php

namespace App\Models\Catalog;

use App\Models\MainModel;
use App\Models\SeoManager;
use App\Traits\Seoable;
use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Builder;

class CatalogCulture extends MainModel
{
    use Translatable, Seoable;

    protected $guarded = ['id'];

    public $translationModel = CatalogCultureTranslation::class;
    public $translationForeignKey = 'culture_id';
    public $translatedAttributes = [
        'title', 'description', 'status', 'slug'
    ];

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function products()
    {
        return $this->belongsToMany(CatalogProduct::class, 'catalog_products_cultures', 'product_id');
    }

    public function protections()
    {
        return $this->belongsToMany(CatalogProtection::class, 'catalog_protections_cultures', 'protection_id');
    }

    public function seo()
    {
        return $this->morphMany(SeoManager::class, 'seoable');
    }

    public function isFavorite()
    {
        return $this->is_favorite;
    }

    public function onPage()
    {
        return $this->on_page;
    }

    public function getImageAttribute($value)
    {
        return $value ?? '/uploads/culture-default.png';
    }

    public function getIconAttribute($value)
    {
        return $value ?? '/uploads/culture-icon-default.png';
    }

    public function scopeIsRoot($query)
    {
        return $query->whereNull('parent_id');
    }

    public function scopeIsNotRoot($query)
    {
        return $query->whereNotNull('parent_id');
    }

    public function scopeActiveTranslation(Builder $query, $locale = null)
    {
        $currentLocale = !is_null($locale) ? $locale : app()->getLocale();

        return $query->where(function($query) use ($currentLocale) {
            $query->orWhereHas('translations', function($query) use ($currentLocale) {
                $query->where('locale', $currentLocale);
            })->orWhere(function($query) use ($currentLocale) {
                $query->orWhere('locale', $currentLocale);
            });
        });
    }

    public function getPath(CatalogCulture $parent = null, $parentPath = null)
    {
        $path = '';

        if (!is_null($parentPath)) {
            $path .= $parentPath . '/';
        } else if (!is_null($this->parent_id)) {
            $path .= ($parent ? $parent->getPath() : $this->parent->getPath()) . '/';
        }

        $path .= $this->slug;

        return $path;
    }
}

app/Models/Catalog/CatalogCultureTranslation.php
<?php

namespace App\Models\Catalog;

use App\Models\MainModel;

class CatalogCultureTranslation extends MainModel
{
    protected $guarded = ['id'];
}

app/Models/Catalog/CatalogDisease.php
<?php

namespace App\Models\Catalog;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class CatalogDisease extends Model
{
    use Translatable;

    protected $guarded = ['id'];

    public $translationModel = CatalogDiseaseTranslation::class;
    public $translationForeignKey = 'disease_id';
    public $translatedAttributes = [
        'title'
    ];

    public function category()
    {
        return $this->belongsTo(CatalogCategory::class, 'category_id');
    }

    public function disableTranslatable()
    {
        return $this->translatedAttributes = [];
    }
}

app/Models/Catalog/CatalogDiseaseTranslation.php
<?php

namespace App\Models\Catalog;


use Illuminate\Database\Eloquent\Model;

class CatalogDiseaseTranslation extends Model
{
    protected $guarded = ['id'];
}

app/Models/Catalog/CatalogProducer.php
<?php

namespace App\Models\Catalog;

use Illuminate\Database\Eloquent\Model;

class CatalogProducer extends Model
{
    protected $guarded = ['id'];
}

app/Models/Catalog/CatalogProductCulture.php
<?php

namespace App\Models\Catalog;

use Illuminate\Database\Eloquent\Model;

class CatalogProductCulture extends Model
{
    protected $table = 'catalog_products_cultures';
}

app/Models/Catalog/CatalogProductDisease.php
<?php

namespace App\Models\Catalog;

use Illuminate\Database\Eloquent\Model;

class CatalogProductDisease extends Model
{
    protected $table = 'catalog_products_diseases';
}

app/Models/Catalog/CatalogProductPhoto.php
<?php

namespace App\Models\Catalog;

use Illuminate\Database\Eloquent\Model;

class CatalogProductPhoto extends Model
{
    protected $table = 'catalog_products_photos';
    protected $guarded = ['id'];
    public $timestamps = false;
}

resources/views/admin/catalog/attribute/_form.blade.php
<div class="card">
    <div class="card-header">
        <div class="card-header__actions">
            <a href="{{ route('admin.catalog.category.edit', $category) }}" class="btn btn-secondary">
                <i class="fa fa-arrow-left"></i>
                <span class="hidden-xs hidden-sm">Вернуться</span>
            </a>
            @if (isset($category) && isset($mode) && $mode === 'edit')
                <button class="btn btn-danger"
                        title="Удалить"
                        data-action="destroy"
                        data-href="{{ route('admin.catalog.category.attribute.destroy', [$category, $attribute]) }}">
                    <i class="fa fa-trash"></i>
                    <span>Удалить</span>
                </button>
            @endif
            <button type="submit" class="btn-success btn"><i class="fa fa-save"></i><span>Сохранить</span></button>
        </div>
    </div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">Ошибка валидации</div>
        @endif
        <div class="form-group {{ $errors->has('locale') ? 'is-invalid' : '' }}">
            <label class="col-form-label">Язык</label>
            <select name="locale" class="form-control select2">
                @foreach ($locales as $langCode => $locale)
                    <option value="{{ $langCode }}"
                        {{ (isset($attribute) && $attribute->locale == $langCode) || old('locale') == $langCode ? 'selected' : '' }}>
                        {{ $locale['title'] }}
                    </option>
                @endforeach
            </select>
            {!! $errors->first('locale','<span class="invalid-feedback">:message</span>') !!}
        </div>
        <div class="form-group {{ $errors->has('type') ? 'is-invalid' : '' }}">
            <label class="col-form-label">Тип атрибута</label>
            <select name="type" class="form-control select2">
                @foreach ($types as $key => $value)
                    <option value="{{ $key }}" {{ isset($attribute) && $attribute->type == $key ? 'selected' : '' }}>{{ $value }}</option>
                @endforeach
            </select>
            {!! $errors->first('type','<span class="invalid-feedback">:message</span>') !!}
        </div>
        <div class="form-group {{ $errors->has('name') ? 'is-invalid' : '' }}">
            <label class="col-form-label">Название</label>
            <input name="name" type="text" class="form-control" value="{{ isset($attribute) ? $attribute->name : old('name') }}">
            {!! $errors->first('name','<span class="invalid-feedback">:message</span>') !!}
        </div>
        <div class="form-group {{ $errors->has('options') ? 'is-invalid' : '' }}">
            <label class="col-form-label">Варианты</label>
            <textarea name="options" class="form-control" rows="3">{{ isset($attribute) && !is_null($attribute->options) ? implode("\n", $attribute->options) : old('options') }}</textarea>
            {!! $errors->first('options','<span class="invalid-feedback">:message</span>') !!}
        </div>
        <div class="form-group {{ $errors->has('sort') ? 'is-invalid' : '' }}">
            <label class="col-form-label">Позиция</label>
            <input name="sort"  type="text" class="form-control" value="{{ isset($attribute) ? $attribute->sort : old('sort') }}">
            {!! $errors->first('sort','<span class="invalid-feedback">:message</span>') !!}
        </div>
        <div class="form-group {{ $errors->has('required') ? 'is-invalid' : '' }}">
            <div class="checkbox">
                <label>
                    @if (isset($attribute))
                        <input type="checkbox" name="required" {{ $attribute->required ? 'checked' : '' }}>
                    @else
                        <input type="checkbox" name="required" {{ old('required') ? 'checked' : ''  }}>
                    @endif
                    Обязательный для заполнения
                </label>
            </div>
            {!! $errors->first('required','<span class="invalid-feedback">:message</span>') !!}
        </div>
        <div class="form-group {{ $errors->has('is_filtered') ? 'is-invalid' : '' }}">
            <div class="checkbox">
                <label>
                    @if (isset($attribute))
                        <input type="checkbox" name="is_filtered" {{ $attribute->is_filtered ? 'checked' : '' }}>
                    @else
                        <input type="checkbox" name="is_filtered" {{ old('is_filtered') ? 'checked' : ''  }}>
                    @endif
                    Показывать в фильтре товаров
                </label>
            </div>
            {!! $errors->first('is_filtered','<span class="invalid-feedback">:message</span>') !!}
        </div>
    </div>
</div>

resources/views/admin/catalog/attribute/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="page-title-area">
        <h4 class="page-title">Каталог - Новый атрибут для категории <i>{{ $category->title }}</i></h4>
        <ul class="breadcrumbs">
            <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
            <li><a href="{{ route('admin.catalog.category.index') }}">Каталог - Все категории</a></li>
            <li><a href="{{ route('admin.catalog.category.edit', $category) }}">{{ $category->title }}</a></li>
            <li><span>Создать новый атрибут</span></li>
        </ul>
    </div>
    <div class="main-content-inner">
        <form action="{{ route('admin.catalog.category.attribute.store', $category) }}" enctype="multipart/form-data" method="POST">
            {{ csrf_field() }}
            @include('admin.catalog.attribute._form', ['mode' => 'create'])
        </form>
    </div>
@endsection

resources/views/admin/catalog/attribute/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="page-title-area">
        <h4 class="page-title">Каталог - Категория - <i>{{ $category->title }}</i></h4>
        <ul class="breadcrumbs">
            <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
            <li><a href="{{ route('admin.catalog.category.index') }}">Каталог - Все категории</a></li>
            <li><a href="{{ route('admin.catalog.category.edit', $category) }}">{{ $category->title }}</a></li>
            <li><span>{{ $attribute->name }}</span></li>
        </ul>
    </div>
    <div class="main-content-inner">
        <form action="{{ route('admin.catalog.category.attribute.update', [$category, $attribute]) }}" enctype="multipart/form-data" method="POST">
            {{ csrf_field() }}
            @method('PUT')
            @include('admin.catalog.attribute._form', ['mode' => 'edit'])
        </form>
    </div>
@endsection

resources/views/admin/catalog/attribute/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="page-title-area">
        <h4 class="page-title">Каталог - Категория</h4>
    </div>
    <div class="main-content-inner">
        <div class="card">
            <div class="card-header">
                <div class="card-header__actions">
                    <a href="{{ route('admin.catalog.category.create') }}" class="btn btn-primary">Создать новую категорию</a>
                </div>
            </div>
            <div class="card-body">
                @if ($categories->isNotEmpty())
                    <div class="single-table">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="text-uppercase bg-light">
                                    <tr>
                                        <th style="min-width: 60px;">ID</th>
                                        <th style="width: 100%;">Заголовок</th>
                                        <th style="min-width: 120px;">Действия</th>
                                    </tr>
                                </thead>
                                <tbody class="sortable">
                                    @foreach($categories as $category)
                                        <tr data-id="{{ $category->id }}">
                                            <th>{{ $category->id }}</th>
                                            <td>{{ $category->title }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <a href="{{ route('admin.catalog.category.edit', $category) }}" class="btn btn-xs btn-primary">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <button class="btn btn-xs btn-secondary btn-sort-handle">
                                                        <i class="fa fa-arrows"></i>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                @else
                    <h4 class="header-title">Empty data</h4>
                @endif
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
		$(function(){
            sortable('.sortable', {
                items: 'tr' ,
                forcePlaceholderSize: true,
                placeholderClass: 'sortable-placeholder',
                hoverClass: 'sortable-hover',
                handle: '.btn-sort-handle',
                itemSerializer: (serializedItem, sortableContainer) => {
                    return {
                        id: serializedItem.node.getAttribute('data-id'),
                        position:  serializedItem.index + 1
                    }
                }
            })[0].addEventListener('sortupdate', function(e) {
                const serialize = sortable('.sortable', 'serialize');
                const items = serialize[0].items;

                $.post({
                    url: '/inside/catalog/category/reorder',
                    data: {
                        items: items
                    },
                    beforeSend: function() {
                        $('.overlay').show();
                    },
                    success: function(response){
                        $('.overlay').hide();
                        $('.sortable').find('.updated').removeClass('updated');
                    }
                });
            });
		});
    </script>
@endpush